# Homepage Config
isSinglePage = true

# Meta Config
description = "Portfolio Website for Ivan Ivanov Mandev @ Game Programmer"

# Header Configuration
avatar = "img/profile-picture.png"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

 # giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]       
    enable = false
    repo = ""
    repoId = ""
    category = "Announcements"
    categoryId = ""
    # mapping = "pathname"  # comment value is the default value
    # strict = 0
    # reactionsEnabled = 1
    # emitMetadata = 0
    # inputPosition = "top"
    # theme = "light"
    # lang = "zh-CN"
    # lazyLoading = true

apple_favicon = "img/apple-touch-icon.png"
normal_favicon32x32 = "img/favicon-32x32.png"
normal_favicon16x16 = "img/favicon-16x16.png"
safari_favicon = "img/safari-pinned-tab.svg"